site_name: Nuki Web API Python Client
site_url: https://barghest89.github.io/nuki-web-api
repo_url: https://github.com/barghest89/nuki-web-api
repo_name: barghest89/nuki-web-api
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.top
  - content.code.copy
extra:
  toc:
    min_level: 2
    max_level: 2
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_source: true
          members: true
          filters:
          - '!^__'
          render_toc: false
          show_attributes: false
nav:
- Home: index.md
- API Reference:
  - Account: reference/account.md
  - AccountUser: reference/accountuser.md
  - Address: reference/address.md
  - AddressReservation: reference/addressreservation.md
  - AddressToken: reference/addresstoken.md
  - AdvancedApi: reference/advancedapi.md
  - ApiKey: reference/apikey.md
  - Company: reference/company.md
  - Notification: reference/notification.md
  - NukiWebAPI: reference/nukiwebapi.md
  - Opener: reference/opener.md
  - Service: reference/service.md
  - Smartlock: reference/smartlock.md
  - SmartlockAuth: reference/smartlockauth.md
  - SmartlockInstance: reference/smartlockinstance.md
  - SmartlockLog: reference/smartlocklog.md
