site_name: Nuki Web API Python Client
site_url: https://barghest89.github.io/nuki-web-api
repo_url: https://github.com/barghest89/nuki-web-api
repo_name: barghest89/nuki-web-api

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - API Reference:
      - NukiWebAPI: reference/nukiwebapi.md
      - Smartlock: reference/smartlock.md
      - Account: reference/account.md
      - AccountUser: reference/accountuser.md
      - ApiKey: reference/apikey.md
      - AdvancedApi: reference/advancedapi.md
      - Address: reference/address.md
      - AddressReservation: reference/addressreservation.md
      - AddressToken: reference/addresstoken.md